# Generated by Django 5.0.7 on 2024-07-19 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0002_organization_parent_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='parent_organization',
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('branch_location', models.CharField(max_length=255, verbose_name='Branch Location')),
                ('branch_phone', models.CharField(max_length=20, verbose_name='Branch Phone')),
                ('branch_email', models.EmailField(max_length=254, verbose_name='Branch Email')),
                ('branch_manager', models.CharField(max_length=255, verbose_name='Branch Manager')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='Organization.organization')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
