# Generated by Django 5.0.7 on 2024-08-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0002_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Template_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
    ]
