# Generated by Django 5.0.7 on 2024-08-07 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('smtp_server', models.CharField(default='smtp.office365.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
