# Generated by Django 5.1 on 2024-08-09 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '0001_initial'),
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Company_name', models.CharField(max_length=100)),
                ('Primary_phone', models.CharField(max_length=100)),
                ('Mobile_phone', models.CharField(max_length=100)),
                ('Primary_Email', models.EmailField(max_length=254)),
                ('Secondary_Email', models.EmailField(max_length=254)),
                ('Company_website', models.CharField(max_length=100)),
                ('Lead_location', models.CharField(max_length=100)),
                ('Notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Client_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.client_type')),
                ('Lead_Followup_Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.lead_followup_status')),
                ('Lead_Industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.industry_type')),
                ('Lead_Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.lead_source')),
                ('Lead_Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.lead_status')),
                ('Products', models.ManyToManyField(blank=True, to='Products.products')),
            ],
        ),
    ]
