# Generated by Django 5.0.7 on 2024-07-19 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0002_lead_assigned_to'),
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='Company_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Company_website',
        ),
        migrations.AddField(
            model_name='lead',
            name='Organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Organization.organization'),
            preserve_default=False,
        ),
    ]
