# Generated by Django 5.0.7 on 2024-07-19 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0003_remove_lead_company_name_remove_lead_company_website_and_more'),
        ('Organization', '0002_organization_parent_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='Branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_leads', to='Organization.organization'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='Organization.organization'),
        ),
    ]
