# Generated by Django 5.0.7 on 2024-07-19 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0004_lead_branch_alter_lead_organization'),
        ('Organization', '0003_remove_organization_parent_organization_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='Branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='Organization.branch'),
        ),
    ]
