# Generated by Django 5.0.7 on 2024-08-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0003_email_template_category'),
        ('email_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='email_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.email_template_category'),
            preserve_default=False,
        ),
    ]
