# Generated by Django 5.0.7 on 2024-08-07 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_products_product_assigned_user_and_more'),
        ('email_templates', '0002_emailtemplate_email_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
    ]
