# Generated by Django 4.2.13 on 2024-06-30 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '0002_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_status', models.BooleanField(default=True)),
                ('Product_Serial_No', models.CharField(max_length=100)),
                ('Product_image', models.ImageField(upload_to='products/')),
                ('Product_Specification', models.TextField()),
                ('Product_description', models.CharField(max_length=100)),
                ('Product_created_at', models.DateTimeField(auto_now_add=True)),
                ('Product_Assigned_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.product_category')),
            ],
        ),
    ]
